version: '3.8'
services:
  app:
    image: teamdrivex
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: teamdrivex
      POSTGRES_HOST_AUTH_METHOD: trust
